"""empty message

Revision ID: 39735e1977ff
Revises: 22109fc72f6b
Create Date: 2026-03-31 15:57:25.452426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39735e1977ff'
down_revision = '22109fc72f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
